services:
  server:
    image: ghcr.io/kanikama0601/googlecalender-schedule-manager-server:main
    ports:
      - "8000:8000"
    volumes:
      - ./server/data:/app/data
    environment:
      # HTTP環境でOAuthを動作させるための設定
      - OAUTHLIB_INSECURE_TRANSPORT=1
    restart: always

  client:
    image: ghcr.io/kanikama0601/googlecalender-schedule-manager-client:main
    ports:
      # Nginx Port:80
      - "80:80"
    depends_on:
      - server
    restart: always
